
proxy:
  ip: 127.0.0.1
  port: 7890
milvus:
  ip: localhost
  port: 19530
server:
  port: 8081

spring:
  ai:
    openai:
      base-url: https://openrouter.ai/api/
      api-key: sk-xxxxxxdsfsfsdfsdfsdfsdfsdf

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cyy.chat.controller
